### ISSUE TITLE
repository size is very high

### ISSUE THREAD

**Issue by weirdwiz** [kbhutani0001/jiit-timetable#11]
somehow the repository is around 30MB while cloning

**Comment by kaybhutani** [comment]
That's because of excel files and images used. Closing this issue for now. If you can reduce the size without affecting the working then make a pull request again

**Comment by weirdwiz** [comment]
The size is not huge because of xlsx files. The `.git` folder is around 29MB maybe one of the branches is very large. If we ignore the `.git` folder the size remains at 1.something MB
